"""add CheckConstraint in abstract base

Revision ID: 71846b30d9ec
Revises: aefaa9502dec
Create Date: 2023-04-11 17:35:37.199235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71846b30d9ec'
down_revision = 'aefaa9502dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
